fix(delimiter): change delimiter
tigergraph/pyTigerGraph pull request #104
Opened 2023-01-25 14:04 UTC by parkererickson-tg

2023-01-25 14:50 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/566/

2023-01-25 16:26 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/567/

2023-01-25 16:26 UTC, qe-tigergraph approved these changes
QE Approved

2023-01-25 16:27 UTC, parkererickson-tg commented
I would also like to run an e2e test once those issues are resolved.

2023-01-30 19:08 UTC, billshitg reviewed
Great job counting all the commas:) Just several minor comments inline there.

2023-01-30 19:41 UTC, parkererickson-tg commented on pyTigerGraph/gds/dataloaders.py
> +                file = "\n".join(["|".join(x) for x in double_list])
I thought they were unnecessary, but it didn't work when I removed them...

2023-01-30 19:52 UTC, parkererickson-tg commented on pyTigerGraph/gds/dataloaders.py
> +                file = "\n".join(["|".join(x) for x in double_list])
Not exactly. I didn't play with it too much either, figured it was existing code. I can take a deeper look though

2023-01-30 21:03 UTC, billshitg commented on pyTigerGraph/gds/dataloaders.py
> +                file = "\n".join(["|".join(x) for x in double_list])
Sure, if you are interested in it. Otherwise, it looks good to me for now. If we really need to squeeze the performance later we can revisit it.

2023-01-30 21:03 UTC, billshitg approved these changes

2023-01-30 22:34 UTC, merged