GML-1241: fix timeout or out-of-memory issue with getVertexCount
tigergraph/pyTigerGraph pull request #131
Opened 2023-03-22 17:44 UTC by billshitg

Issue
* The `/graph/{graph_name}/vertices` endpoint with `count_only=true` is too slow on large graphs and sometime it even causes GPE to crash due to OOM.

Solution
* Use `/builtins` with `stat_vertex_number` whenever possible (i.e., `where` clause is not needed).

2023-03-22 18:56 UTC, parkererickson-tg approved these changes
Is this up-to-date enough for us? My understanding this is the metadata endpoint that may not be super recent or correct.

2023-03-22 20:35 UTC, billshitg commented
Good question. Let me ask around

2023-03-23 17:39 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/693/

2023-03-23 18:48 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/694/

2023-03-23 22:18 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/695/

2023-03-23 22:18 UTC, qe-tigergraph approved these changes
QE Approved

2023-03-23 23:45 UTC, billshitg commented
I added a realtime parameter and relevant docstrings. Please let me know if it looks good to you. Thanks!

2023-03-25 01:15 UTC, parkererickson-tg commented
Duplicated by #132. Closing.

2023-03-25 01:15 UTC, closed without merging