GML-1238: add SSL support for Kafka
tigergraph/pyTigerGraph pull request #133
Opened 2023-03-24 23:16 UTC by billshitg

* Add logics to pass SSL relevant information for Kafka
* Use the new, refactored Kafka UDF

2023-03-25 01:19 UTC, parkererickson-tg approved these changes

2023-04-06 16:16 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/726/

2023-04-10 10:18 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/728/

2023-04-10 10:18 UTC, qe-tigergraph approved these changes
QE Approved

2023-04-10 18:30 UTC, merged