feat(runInstalledQuery and runAlgorithm): add memory limit header
tigergraph/pyTigerGraph pull request #137
Opened 2023-03-28 15:12 UTC by parkererickson-tg

2023-03-28 21:57 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/706/

2023-03-28 23:06 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/707/

2023-03-29 00:52 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/708/

2023-03-29 02:37 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/709/

2023-03-29 06:22 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/710/

2023-03-29 06:22 UTC, qe-tigergraph approved these changes
QE Approved

2023-03-31 20:09 UTC, parkererickson-tg commented on pyTigerGraph/gds/featurizer.py
> +            memoryLimit:
Added.

2023-03-31 20:09 UTC, merged