Gml 1207 add more metrics
tigergraph/pyTigerGraph pull request #138
Opened 2023-03-31 19:24 UTC by parkererickson-tg

2023-03-31 23:23 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/714/

2023-03-31 23:23 UTC, qe-tigergraph approved these changes
QE Approved

2023-04-04 18:34 UTC, billshitg approved these changes
LGTM. There are some nitpicking issues but they don't affect the functioning of the code

2023-04-04 18:34 UTC, billshitg commented on pyTigerGraph/gds/metrics.py
> +        self._count += int(len(preds))
Just nitpicking: len() is already int

2023-04-04 18:34 UTC, billshitg commented on pyTigerGraph/gds/metrics.py
> +            Number of classes in your classification task.
Is k the number of classes?

2023-04-04 18:34 UTC, billshitg commented on pyTigerGraph/gds/metrics.py
> +            Number of classes in your classification task.
Same here

2023-04-04 18:34 UTC, billshitg commented on tests/test_gds_metrics.py
> +        measure = ConfusionMatrix(num_classes=2)
Do we have test for num_classes>2 for any of the the ConfusionMatrix related metrics?

2023-04-04 20:27 UTC, billshitg approved these changes
thanks for resolving the minor comments. look good to me

2023-04-04 20:52 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/717/

2023-04-04 21:41 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/718/

2023-04-04 22:38 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/719/

2023-04-05 02:38 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/720/

2023-04-05 03:39 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/721/

2023-04-05 14:18 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/723/

2023-04-05 21:51 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/724/

2023-04-05 21:51 UTC, qe-tigergraph approved these changes
QE Approved

2023-04-05 21:51 UTC, merged