Fix docstring of `graphLoader`
tigergraph/pyTigerGraph pull request #181
Opened 2023-07-25 05:04 UTC by OldPanda

The default value of `output_format` in function `graphLoader` should be `PyG` according to the function signature.

2023-07-25 19:49 UTC, parkererickson-tg commented
Thanks for the fix! We will get it merged in.

2023-07-25 20:49 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/917/

2023-07-26 00:03 UTC, OldPanda commented
Hmm, why updating a line of comment fails the e2e test... 🤔

2023-07-26 00:11 UTC, parkererickson-tg commented
Because our tests broke for some reason... 🙃 We will get it through though. Thanks again for the fix.

2023-07-26 18:06 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/919/

2023-07-26 19:24 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/920/

2023-07-28 20:37 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/926/

2023-07-28 22:14 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/927/

2023-08-01 18:34 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/931/

2023-08-01 19:40 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/932/

2023-08-01 20:08 UTC, merged