Gml 1378 oo schema docs
tigergraph/pyTigerGraph pull request #189
Opened 2023-08-31 17:34 UTC by parkererickson-tg

2023-08-31 18:07 UTC, billshitg approved these changes

2023-08-31 18:07 UTC, billshitg commented on pyTigerGraph/schema.py
> +        discriminator: str = "opened_on"
Sorry I forgot: do we allow the use of multiple attributes as discriminator?

2023-08-31 18:33 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/960/

2023-08-31 18:40 UTC, parkererickson-tg commented on pyTigerGraph/schema.py
> +    primary_id: str = "id"
Correct. Will denote that.

2023-09-01 02:04 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/962/

2023-09-01 15:07 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/967/

2023-09-01 16:40 UTC, merged