Add heterogeneous graph support
tigergraph/pyTigerGraph pull request #20
Opened 2022-06-01 21:05 UTC by tg-bill

Code change:
1. Update NeighborLoader, GraphLoader, VertexLoader, and EdgeLoader and their corresponding queries to load from heterogeneous graphs. 
2. User can specify what types of vertices/edges to get and what attributes to get for each vertex/edge type.
3. Output is PyG HeteroData. DGL heterograph is not supported yet.

Testing:
1. Unit tests added and passed.

2022-06-02 20:39 UTC, parkererickson approved these changes

2022-06-02 20:46 UTC, parkererickson requested changes
The docstrings need to be changed in order to reflect that to use on heterogenous graphs you pass in a dictionary (for example {"VERTEX_TYPE": ["ATTRIBUTES"]}.

2022-06-08 00:01 UTC, tg-bill commented
> 

Just updated the docstrings. how does it look

2022-06-08 02:53 UTC, parkererickson approved these changes

2022-06-08 02:54 UTC, parkererickson commented
Looks good!

2022-06-08 16:17 UTC, nzarayeneh approved these changes

2022-06-08 17:53 UTC, merged