feat(getToken): allow user to get token using user/pass
tigergraph/pyTigerGraph pull request #200
Opened 2023-11-20 19:49 UTC by parkererickson-tg

2023-12-06 19:49 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1022/

2023-12-07 22:12 UTC, billshitg commented on pyTigerGraph/pyTigerGraphAuth.py
> +            print(res)
Is this print intended?

2023-12-07 22:27 UTC, parkererickson-tg commented on pyTigerGraph/pyTigerGraphAuth.py
> +            print(res)
Nope. Removed

2023-12-08 00:48 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1028/

2023-12-08 01:38 UTC, billshitg approved these changes

2023-12-08 01:42 UTC, merged