fix(getToken): fix getToken()
tigergraph/pyTigerGraph pull request #212
Opened 2024-02-13 21:33 UTC by parkererickson-tg

2024-02-13 22:33 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1049/

2024-02-13 23:42 UTC, billshitg commented on pyTigerGraph/pyTigerGraphAuth.py
> +        elif not(success) and (int(s) < 3 or (int(s) == 3 and int(m) < 5)):
Seems like it is still missing the case when secret is given and the version is above 3.5. Do we use the secret to get token or use username/password?

2024-02-14 00:20 UTC, parkererickson-tg commented
The case of secret given and over 3.5 should be covered in the if block below checking if the first if was success or not. This was due to the change of GET vs POST that was changed with v3.5.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: billshitg ***@***.***>
Sent: Tuesday, February 13, 2024 5:42:20 PM
To: tigergraph/pyTigerGraph ***@***.***>
Cc: parkererickson-tg ***@***.***>; Author ***@***.***>
Subject: Re: [tigergraph/pyTigerGraph] fix(getToken): fix getToken() (PR #212)


@billshitg commented on this pull request.

________________________________

In pyTigerGraph/pyTigerGraphAuth.py<https://github.com/tigergraph/pyTigerGraph/pull/212#discussion_r1488723923>:

> @@ -231,7 +231,7 @@ def getToken(self, secret: str = None, setToken: bool = True, lifetime: int = No
         elif not(success) and not(secret):
             res = self._post(self.restppUrl+"/requesttoken", authMode="pwd", data=str({"graph": self.graphname}), resKey="results")
             success = True
-        else:
+        elif not(success) and (int(s) < 3 or (int(s) == 3 and int(m) < 5)):


Seems like it is still missing the case when secret is given and the version is above 3.5. Do we use the secret to get token or use username/password?

—
Reply to this email directly, view it on GitHub<https://github.com/tigergraph/pyTigerGraph/pull/212#pullrequestreview-1879138004>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A36AN3WJ74ZABYVNJX3Y2ODYTP25ZAVCNFSM6AAAAABDHG44HGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNZZGEZTQMBQGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-14 02:07 UTC, billshitg commented
Is it this line: `elif not(success) and not(secret)`? If secret is given, would not(secret) be False, and this condition be False?

2024-02-14 03:16 UTC, parkererickson-tg commented
No, it is line 238-248:
```py
if not success:
            try:
                data = {"secret": secret}

                if lifetime:
                    data["lifetime"] = str(lifetime)

                res = json.loads(requests.post(self.restppUrl + "/requesttoken",
                    data=json.dumps(data), verify=False).text)
            except Exception as e:
                raise e
```

(I don't know why it was implemented this way either)

2024-02-14 20:55 UTC, billshitg approved these changes

2024-02-15 15:35 UTC, merged