vertexMustExist
tigergraph/pyTigerGraph pull request #244
Opened 2024-08-05 21:08 UTC by RobRossmiller-TG

[GML-1436](https://graphsql.atlassian.net/browse/GML-1436)

Some changes are just the [ruff formatter](https://docs.astral.sh/ruff/formatter/#:~:text=The%20Ruff%20formatter%20is%20an,1.2.)

Changes include adding the `vertexMustExist` param to `upsertEdge`, `upsertEdges`, and `upsertEdgeDataFrame`. It defaults to False.

2024-08-05 22:02 UTC, parkererickson-tg approved these changes

2024-08-05 22:03 UTC, luzhoutg approved these changes

2024-08-06 14:47 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1142/

2024-08-06 19:09 UTC, qe-tigergraph requested changes
Unit Test: SUCCESS, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1143/

2024-08-06 20:18 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1145/

2024-08-06 21:47 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/1146/

2024-08-06 21:47 UTC, qe-tigergraph approved these changes
QE Approved

2024-08-07 16:34 UTC, merged