Install udf
tigergraph/pyTigerGraph pull request #28
Opened 2022-06-29 01:16 UTC by nzarayeneh

2022-06-29 14:43 UTC, parkererickson requested changes
Looks like there was a merge conflict. These need to be resolved before merge.

2022-06-29 16:32 UTC, tg-bill commented on pyTigerGraph/gds/featurizer.py
> +<<<<<<< HEAD
And here as well

2022-06-29 16:42 UTC, nzarayeneh commented
> Looks like there was a merge conflict. These need to be resolved before merge.

yeah, I am going to fix it

2022-06-29 17:07 UTC, parkererickson commented
Can you specify that `global_schema` in `installAlgorithm` is only needed for FastRP? just want to have clarity in where to use it.

2022-06-29 20:22 UTC, nzarayeneh commented
I mentioned those algorithms that are note schema free, though maybe we
might have more in future, but if not yeah we can change it to just for
fastRP

On Wed, Jun 29, 2022 at 10:08 AM Parker Erickson ***@***.***>
wrote:

> Can you specify that global_schema in installAlgorithm is only needed for
> FastRP? just want to have clarity in where to use it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tigergraph/pyTigerGraph/pull/28#issuecomment-1170249871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXHW4FJWYZUPEXVN2OXCAWTVRR7HLANCNFSM52EAVVHQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-01 15:20 UTC, tg-bill approved these changes

2022-07-01 15:35 UTC, merged