GML-1049: get and check parameters for query
tigergraph/pyTigerGraph pull request #76
Opened 2022-11-17 21:16 UTC by billshitg

Code change
* Allow user to get parameters for any built-in algo using getParams function
* Validate input parameters to runAlgorithm

2022-11-17 21:38 UTC, parkererickson-tg approved these changes

2022-11-17 22:00 UTC, qe-tigergraph requested changes
Unit Test: FAILED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/362/

2022-11-18 02:46 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/364/

2022-11-18 02:46 UTC, qe-tigergraph approved these changes
QE Approved

2022-11-18 18:33 UTC, merged