fix(tests): use qa db in splitter and utilities test
tigergraph/pyTigerGraph pull request #83
Opened 2022-12-08 23:35 UTC by billshitg

2022-12-08 23:39 UTC, parkererickson-tg approved these changes

2022-12-09 00:19 UTC, qe-tigergraph requested changes
Unit Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/397/

2022-12-09 01:41 UTC, qe-tigergraph reviewed
Unit Test: SUCCESS, e2e Test: SKIPPED, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/406/

2022-12-09 01:41 UTC, qe-tigergraph approved these changes
QE Approved

2022-12-09 01:43 UTC, merged